services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: lekhantra-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env.docker

    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: lekhantra-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped
